name: 问题反馈
description: 提交非预期行为、错误或缺陷报告
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢提交问题反馈！请尽可能详细地填写以下内容，以帮助我们理解和解决问题。
        
  - type: textarea
    id: problem-description
    attributes:
      label: 问题现象
      description: 尽可能详细地描述问题的表现。
      placeholder: 在此描述问题...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        如果问题不能通过某些步骤稳定重现，请在错误发生时关注`Ctrl+Shift+I`开发者工具中的`Console`/`控制台`中的有关提示信息，将遇到问题时的错误信息截图上传。

  - type: textarea
    id: reproduce-steps
    attributes:
      label: 复现操作
      description: 描述重现问题所需要的步骤或设置项。如果不能稳定重现，请说明问题的发生频率，并上传错误提示信息。
      placeholder: |
        1. 打开插件的xxx功能；
        2. 打开xxx文档；
        3. 问题出现；
    validations:
      required: true

  - type: textarea
    id: screenshots-or-recordings
    attributes:
      label: 截图或录屏说明
      description: 请上传截图或录屏来演示问题。（可不填）
      placeholder: 在此提供截图或录屏...
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: 预期行为
      description: 描述你认为插件应当表现出怎样的行为或结果（可不填）
      placeholder: 在此描述预期行为...

  - type: textarea
    attributes:
      label: 设备和系统信息
      description: |
        示例:
          - **操作系统**: Windows11 24H2
          - **Siyuan**：v3.1.25
          - **插件版本**：v0.2.0
      value: |
          - 操作系统：
          - Siyuan：
          - 插件版本：
      render: markdown
    validations:
      required: true

  - type: checkboxes
    id: check_list
    attributes:
      label: 检查单
      description: 在提交前，请确认这些事项
      options:
      - label: 我已经查询了issue列表，我认为没有人反馈过类似问题
        required: true
      - label: 我已经将插件升级到最新版本
        required: true

  - type: textarea
    id: additional-info
    attributes:
      label: 其他补充信息
      description: 如有其他相关信息，请在此提供。例如插件设置、思源设置等。
      placeholder: 在此提供补充信息...
